name: Verify Email Step Workflow

on:
  workflow_dispatch:   # manual trigger
  push:
    branches:
      - main

jobs:
  email-step-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 24f1001768@ds.study.iitm.ac.in
        run: echo "This step name includes the required email"
